[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "freetype"
version = "0.1.0"
edition = "2018"
links = "freetype"
build = "build.rs"

[dependencies]
fixed = "1.23"

[build-dependencies]
cc = {version="1.0", features = ["parallel"]}
