[package]
name = "wezterm"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = {version="0.4", default-features=false}
clap = {version="4.0", features=["derive", "wrap_help"]}
clap_complete = "4.4"
clap_complete_fig = "4.0"
codec = { path = "../codec" }
config = { path = "../config" }
env-bootstrap = { path = "../env-bootstrap" }
filedescriptor = { version="0.8", path = "../filedescriptor" }
hostname = "0.4"
image = "0.25"
libc = "0.2"
log = "0.4"
mux = { path = "../mux" }
portable-pty = { path = "../pty" }
promise = { path = "../promise" }
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
shell-words = "1.1"
smol = "1.2"
tabout = { path = "../tabout" }
tempfile = "3.3"
termwiz = { path = "../termwiz" }
termwiz-funcs = { path = "../lua-api-crates/termwiz-funcs" }
textwrap = "0.16"
umask = { path = "../umask" }
url = "2"
wezterm-client = { path = "../wezterm-client" }
wezterm-gui-subcommands = { path = "../wezterm-gui-subcommands" }
wezterm-term = { path = "../term" }

[target."cfg(unix)".dependencies]
termios = "0.3"

[target."cfg(windows)".dependencies.winapi]
features = [
    "winbase",
    "winerror",
    "winnls",
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "synchapi",
]
version = "0.3"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.7"
cc = "1.0"
