[package]
name = "wezterm"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0"

[dependencies]
anyhow = "1.0"
codec = { path = "../codec" }
config = { path = "../config" }
env-bootstrap = { path = "../env-bootstrap" }
filedescriptor = { version="0.7", path = "../filedescriptor" }
hostname = "0.3"
log = "0.4"
mux = { path = "../mux" }
portable-pty = { path = "../pty" }
promise = { path = "../promise" }
smol = "1.2"
structopt = "0.3"
tabout = { path = "../tabout" }
termwiz = { path = "../termwiz" }
textwrap = "0.13"
umask = { path = "../umask" }
url = "2"
wezterm-client = { path = "../wezterm-client" }
wezterm-gui-subcommands = { path = "../wezterm-gui-subcommands" }
wezterm-term = { path = "../term" }

