# Run `rustfmt --config-help` to see available config options.
# Please keep these in alphabetical order.
closure_block_indent_threshold = 1
condense_wildcard_suffixes = true
error_on_line_overflow = false
error_on_line_overflow_comments = false
# Too many derives can cause line length limits to be exceeded. rustfmt-nightly
# 0.2.5 doesn't appear to pay attention to this.
merge_derives = false
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
# Override the Nuclide/Atom default tab spacing.
tab_spaces = 4
use_try_shorthand = true
write_mode = "replace"
