language: rust
sudo: required

cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux
#  - windows

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

before_script:
  - rustup component add rustfmt-preview
  - PREFIX=$TRAVIS_BUILD_DIR ./ci/build_harfbuzz.sh

script:
  - "if [[ \"$TRAVIS_RUST_VERSION\" == \"stable\" ]] ; then cargo fmt --all -- --check ; else true ; fi"
  - cargo build --verbose --all
  - cargo test --verbose --all

addons:
  apt:
    packages:
      - binutils-dev
      - cmake
      - gcc
      - xorg-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libegl1-mesa-dev
      - libelf-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libiberty-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - ragel

env:
  global:
      - PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/lib/pkgconfig

