[package]
name = "wezterm-gui"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.3"
cc = "1.0"

[dependencies]
anyhow = "1.0"
bitflags = "1.0"
codec = { path = "../codec" }
config = { path = "../config" }
dirs = "2.0"
downcast-rs = "1.0"
env-bootstrap = { path = "../env-bootstrap" }
euclid = "0.20"
filedescriptor = { version="0.7", path = "../filedescriptor" }
hdrhistogram = "7.1"
http_req = {version="0.6", default-features=false, features=["rust-tls"]}
image = "0.23"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
lru = "0.5"
luahelper = { path = "../luahelper" }
metrics = { version="0.12", features=["std"]}
mlua = "0.4"
mux = { path = "../mux" }
open = "1.4"
openssl = "0.10"
palette = "0.5"
portable-pty = { path = "../pty", features = ["serde_support", "ssh"]}
pretty_env_logger = "0.4"
promise = { path = "../promise" }
pulldown-cmark = "0.8"
rangeset = { path = "../rangeset" }
ratelim= { path = "../ratelim" }
regex = "1"
serde = {version="1.0", features = ["rc", "derive"]}
serde_json = "1.0"
serial = "0.4"
smol = "1.2"
structopt = "0.3"
tabout = { path = "../tabout" }
terminfo = "0.7"
termwiz = { path = "../termwiz" }
textwrap = "0.12"
thiserror = "1.0"
umask = { path = "../umask" }
unicode-normalization = "0.1"
unicode-segmentation = "1.6"
unicode-width = "0.1"
url = "2"
walkdir = "2"
wezterm-client = { path = "../wezterm-client" }
wezterm-font = { path = "../wezterm-font" }
wezterm-gui-subcommands = { path = "../wezterm-gui-subcommands" }
wezterm-term = { path = "../term", features=["use_serde"] }
window = { path = "../window", features=["opengl", "wayland"]}

[target.'cfg(not(windows))'.dependencies]
# show a notification
notify-rust = "3"

[target."cfg(windows)".dependencies]
shared_library = "0.1"
uds_windows = "0.1"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
    "winsock2",
]}
winrt-notification = "0.2"

[features]
default = ["vendor_openssl"]
# FIXME: find a way to magically disable vendor_openssl only on linux!
vendor_openssl = ["openssl/vendored"]

