[package]
name = "wezterm-gui"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
build = "build.rs"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wayland"]
wayland = ["window/wayland"]

[build-dependencies]
anyhow = "1.0"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.3"
cc = "1.0"
windows = "0.11"

[dependencies]
anyhow = "1.0"
bitflags = "1.0"
chrono = {version="0.4", features=["unstable-locales"]}
codec = { path = "../codec" }
config = { path = "../config" }
downcast-rs = "1.0"
env-bootstrap = { path = "../env-bootstrap" }
euclid = "0.22"
filedescriptor = { version="0.8", path = "../filedescriptor" }
hdrhistogram = "7.1"
http_req = "0.8"
image = "0.23"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
lru = "0.6"
luahelper = { path = "../luahelper" }
metrics = { version="0.17", features=["std"]}
mlua = "0.5"
mux = { path = "../mux" }
open = "1.4"
ordered-float = "2.7"
palette = "0.6"
percent-encoding = "2"
portable-pty = { path = "../pty", features = ["serde_support", "ssh"]}
promise = { path = "../promise" }
pulldown-cmark = "0.8"
rangeset = { path = "../rangeset" }
ratelim= { path = "../ratelim" }
regex = "1"
serde = {version="1.0", features = ["rc", "derive"]}
serde_json = "1.0"
serial = "0.4"
smol = "1.2"
structopt = "0.3"
tabout = { path = "../tabout" }
terminfo = "0.7"
termwiz = { path = "../termwiz" }
textwrap = "0.14"
thiserror = "1.0"
tiny-skia = "0.5"
umask = { path = "../umask" }
unicode-normalization = "0.1"
unicode-segmentation = "1.7"
unicode-width = "0.1"
url = "2"
walkdir = "2"
wezterm-client = { path = "../wezterm-client" }
wezterm-font = { path = "../wezterm-font" }
wezterm-gui-subcommands = { path = "../wezterm-gui-subcommands" }
wezterm-mux-server-impl = { path = "../wezterm-mux-server-impl" }
wezterm-ssh = { path = "../wezterm-ssh" }
wezterm-term = { path = "../term", features=["use_serde"] }
wezterm-toast-notification = { path = "../wezterm-toast-notification" }
window = { path = "../window" }

[target."cfg(windows)".dependencies]
shared_library = "0.1"
windows = "0.11"
winapi = { version = "0.3", features = [
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "synchapi",
    "winsock2",
]}

[dev-dependencies]
k9 = "0.11.0"
pretty_env_logger = "0.4"
benchmarking = "0.4"
