[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "term"
version = "0.1.0"

[dependencies]
bitflags = "~1.0"
failure = "~0.1"
image = "~0.19"
ordered-float = "~0.5"
unicode-segmentation = "~1.2"
unicode-width = "~0.1"

[dependencies.termwiz]
path = "../termwiz"

[features]
debug-escape-sequences = []
