[package]
authors = ["Wez Furlong"]
name = "termwiz"
version = "0.11.0"
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Terminal Wizardry for Unix and Windows"
license = "MIT"
documentation = "https://docs.rs/termwiz"
keywords = ["terminal", "readline", "console", "curses"]
readme = "README.md"

[dependencies]
base64 = "0.10"
bitflags = "1.0"
cassowary = {version="0.3", optional=true}
anyhow = "1.0"
filedescriptor = { version="0.7", path = "../filedescriptor" }
fnv = {version="1.0", optional=true}
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
memmem = "0.1"
num-traits = "0.2"
ordered-float = "2.0"
regex = "1"
semver = "0.9"
serde = {version="1.0", features = ["rc", "derive"], optional=true}
terminfo = "0.7"
unicode-segmentation = "1.7"
unicode-width = "0.1"
xi-unicode = "0.2"
vtparse = { version="0.3", path="../vtparse" }

[features]
widgets = ["cassowary", "fnv"]
use_serde = ["serde"]

[dev-dependencies]
varbincode = "0.1"
pretty_assertions = "0.6"

[dependencies.num-derive]
features = ["full-syntax"]
version = "0.2"
[target."cfg(unix)".dependencies]
signal-hook = "0.1"
termios = "0.3"
[target."cfg(windows)".dependencies.winapi]
features = [
    "winbase",
    "winerror",
    "winuser",
    "consoleapi",
    "handleapi",
    "fileapi",
    "synchapi",
]
version = "0.3"
