[package]
name = "mux"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.13"
bintree = { path = "../bintree" }
config = { path = "../config" }
crossbeam = "0.8"
downcast-rs = "1.0"
filedescriptor = { version="0.8", path = "../filedescriptor" }
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
luahelper = { path = "../luahelper" }
metrics = { version="0.16", features=["std"]}
portable-pty = { path = "../pty", features = ["serde_support"]}
promise = { path = "../promise" }
rangeset = { path = "../rangeset" }
ratelim= { path = "../ratelim" }
regex = "1"
serde = {version="1.0", features = ["rc", "derive"]}
smol = "1.2"
terminfo = "0.7"
termwiz = { path = "../termwiz" }
textwrap = "0.14"
thiserror = "1.0"
tmux-cc = { path = "../tmux-cc" }
unicode-segmentation = "1.7"
url = "2"
wezterm-ssh = { path = "../wezterm-ssh" }
wezterm-term = { path = "../term", features=["use_serde"] }

[target.'cfg(any(windows, target_os="linux", target_os="macos"))'.dependencies]
sysinfo = "0.16"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "handleapi",
    "processthreadsapi"
]}

[dev-dependencies]
k9 = "0.11"
