[package]
name = "config"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
vergen = "3"

[dev-dependencies]
pretty_env_logger = "0.4"

[dependencies]
anyhow = "1.0"
bitflags = "1.0"
bstr = "0.2"
dirs-next = "2.0"
filenamegen = "0.2"
hostname = "0.3"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
luahelper = { path = "../luahelper" }
mlua = {version="0.5", features=["vendored", "lua54", "async", "send"]}
# file change notification
notify = "4.0"
portable-pty = { path = "../pty", features = ["serde_support"]}
promise = { path = "../promise" }
serde = {version="1.0", features = ["rc", "derive"]}
smol = "1.2"
termwiz = { path = "../termwiz" }
toml = "0.5"
umask = { path = "../umask" }
wezterm-input-types = { path = "../wezterm-input-types" }
wezterm-term = { path = "../term", features=["use_serde"] }

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = ["winuser"]}
