[package]
name = "filedescriptor"
version = "0.2.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wzsh"
description = "More ergonomic wrappers around RawFd and RawHandle"
license = "MIT"
documentation = "https://docs.rs/filedescriptor"
readme = "README.md"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
libc = "0.2"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [
    "winuser",
    "handleapi",
    "fileapi",
    "namedpipeapi",
    "processthreadsapi",
    "winsock2"
]}
