[package]
name = "wezterm-bidi"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/wez/wezterm"
description = "The Unicode Bidi Algorithm (UBA)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
use_serde = ["serde"]

[dependencies]
log = "0.4"
serde = {version="1.0", features = ["derive"], optional=true}
wezterm-dynamic = { path = "../wezterm-dynamic" }

[dev-dependencies]
k9 = "0.11.0"
env_logger = "0.9"
