[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"
build = "build.rs"

[dev-dependencies]
k9 = "0.12.0"

[build-dependencies]
gl_generator = "0.14"

[features]
wayland = ["wayland-client", "smithay-client-toolkit", "wayland-egl", "wayland-protocols"]

[dependencies]
async-channel = "1.6"
async-io = "1.1"
async-task = "4.0"
async-trait = "0.1"
anyhow = "1.0"
bytes = "1.0"
config = { path = "../config" }
downcast-rs = "1.0"
thiserror = "1.0"
bitflags = "1.3"
euclid = "0.22"
guillotiere = "0.6"
lazy_static = "1.4"
libloading = "0.6"
line_drawing = "0.8"
log = "0.4"
metrics = { version="0.17", features=["std"]}
promise = { path = "../promise" }
raw-window-handle = "0.5"
resize = "0.5"
serde = {version="1.0", features = ["rc", "derive"]}
tiny-skia = "0.11"
glium = { version = "0.34", default-features = false }
url = "2"
wezterm-bidi = { path = "../bidi" }
wezterm-color-types = { path = "../color-types" }
wezterm-font = { path = "../wezterm-font" }
wezterm-input-types = { path = "../wezterm-input-types" }

[target."cfg(windows)".dependencies]
clipboard-win = "2.2"
shared_library = "0.1"
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "imm",
    "libloaderapi",
    "shellscalingapi",
    "synchapi",
    "sysinfoapi",
    "winerror",
    "winuser",
]}
windows = { version="0.33.0", features = [
    "UI_ViewManagement",
    "Win32_Devices_Display",
]}
winreg = "0.10"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dirs-next = "2.0"
filedescriptor = { version="0.8", path = "../filedescriptor" }
futures-util = "0.3"
futures-lite = "1.12"
x11 = {version ="2.21", features = ["xlib_xcb", "xlib"]}
xcb = {version="1.3", features=["render", "randr", "dri2", "xkb", "xlib_xcb", "present", "as-raw-xcb-connection"]}
xkbcommon = { version = "0.7.0", features = ["x11", "wayland"] }
mio = {version="0.8", features=["os-ext"]}
libc = "0.2"
xcb-imdkit = { version="0.3", git="https://github.com/wez/xcb-imdkit-rs.git", rev="215ce4b08ac9c4822e541efd4f4ffb1062806051"}
zbus = "3.14"
zvariant = "3.15"

smithay-client-toolkit = {version = "0.18", default-features=false, optional=true}
wayland-protocols = {version="0.31", optional=true}
wayland-client = {version="0.31", optional=true}
wayland-egl = {version="0.32", optional=true}

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
core-foundation = "0.7"
core-graphics = "0.19"
cgl = "0.3"
plist = "1.3"
shlex = "1.1"
