[package]
name = "window"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
repository = "https://github.com/wez/wezterm"
description = "Cross platform window setup and render"
license = "MIT"
build = "build.rs"

[dev-dependencies]
k9 = "0.11.0"

[build-dependencies]
gl_generator = "0.14"

[features]
wayland = ["wayland-client", "smithay-client-toolkit", "wayland-egl", "wayland-protocols"]

[dependencies]
async-channel = "1.6"
async-io = "1.1"
async-task = "4.0"
async-trait = "0.1"
anyhow = "1.0"
bytes = "1.0"
config = { path = "../config" }
thiserror = "1.0"
bitflags = "1.3"
euclid = "0.22"
guillotiere = "0.6"
lazy_static = "1.4"
libloading = "0.6"
line_drawing = "0.8"
log = "0.4"
metrics = { version="0.17", features=["std"]}
promise = { path = "../promise" }
raw-window-handle = "0.5"
resize = "0.5"
serde = {version="1.0", features = ["rc", "derive"]}
tiny-skia = "0.8"
glium = { version = "0.31", default-features = false }
url = "2"
wezterm-bidi = { path = "../bidi" }
wezterm-color-types = { path = "../color-types" }
wezterm-font = { path = "../wezterm-font" }
wezterm-input-types = { path = "../wezterm-input-types" }

[target."cfg(windows)".dependencies]
clipboard-win = "2.2"
shared_library = "0.1"
winapi = { version = "0.3", features = [
    "dwmapi",
    "handleapi",
    "imm",
    "libloaderapi",
    "synchapi",
    "sysinfoapi",
    "winerror",
    "winuser",
]}
windows = { version="0.33.0", features = [
    "UI_ViewManagement",
    "Win32_Devices_Display",
]}
winreg = "0.10"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dirs-next = "2.0"
filedescriptor = { version="0.8", path = "../filedescriptor" }
x11 = {version ="2.19", features = ["xlib_xcb", "xlib"]}
xcb = {version="1.1.1", features=["render", "randr", "dri2", "xkb", "xlib_xcb", "present"]}
xkbcommon = { version = "0.5.0", features = ["x11", "wayland"] }
mio = {version="0.8", features=["os-ext"]}
libc = "0.2"
smithay-client-toolkit = {version = "0.15", default-features=false, optional=true}
wayland-protocols = {version="0.29", optional=true}
wayland-client = {version="0.29", optional=true}
wayland-egl = {version="0.29", optional=true}
xcb-imdkit = { version="0.2", git="https://github.com/wez/xcb-imdkit-rs.git", branch="waiting-on-release"}
serde = {version="1.0", features = ["derive"]}
zbus = "3.0"
zvariant = "3.6"
futures-util = "0.3"

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20"
objc = "0.2"
clipboard_macos = "0.1"
core-foundation = "0.7"
core-graphics = "0.19"
cgl = "0.3"
