[package]
authors = ["Wez Furlong <wez@wezfurlong.org>"]
name = "promise"
version = "0.2.0"
edition = "2018"

[dependencies]
async-task = "4.0"
async-std = "1.4"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
flume = "0.9"
