[package]
name = "color-funcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = { path = "../../config" }
csscolorparser = {version="0.6", features=["lab"]}
deltae = "0.3"
image = "0.25"
lazy_static = "1.4"
log = "0.4"
lru = "0.7"
luahelper = { path = "../../luahelper" }
plist = "1.3"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
serde_yaml = "0.9"
wezterm-dynamic = { path = "../../wezterm-dynamic" }
wezterm-term = { path = "../../term", features=["use_serde"] }
