[package]
name = "rangeset"
version = "0.1.0"
authors = ["Wez Furlong <wez@wezfurlong.org>"]
edition = "2018"

[dependencies]
num = "0.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "rangeset"
harness = false

