name: alpine3.17

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/gen_alpine3.17.yml"
      - "assets/fonts/**/*"
      - "assets/icon/*"
      - "assets/open-wezterm-here"
      - "assets/shell-completion/**/*"
      - "assets/shell-integration/**/*"
      - "assets/wezterm-nautilus.py"
      - "assets/wezterm.appdata.xml"
      - "assets/wezterm.desktop"
      - "ci/deploy.sh"
      - "ci/tag-name.sh"
      - "get-deps"
      - "termwiz/data/wezterm.terminfo"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "alpine:3.17"
    env:
      RUSTFLAGS: "-C target-feature=-crt-static"

    steps:
      - name: "Upgrade system"
        shell: sh
        run: "apk upgrade --update-cache"
      - name: "Install CI dependencies"
        shell: sh
        run: "apk add nodejs zstd wget bash coreutils tar findutils"
      - name: "Allow root login"
        shell: bash
        run: "sed 's/root:!/root:*/g' -i /etc/shadow"
      - name: "Install git"
        shell: bash
        run: "apk add git"
      - name: "Install curl"
        shell: bash
        run: "apk add curl"
      - name: "Install openssh"
        shell: bash
        run: "apk add openssh"
      - name: "Workaround git permissions issue"
        shell: bash
        run: "git config --global --add safe.directory /__w/wezterm/wezterm"
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Cache cargo"
        uses: Swatinem/rust-cache@v2
        with:
          key: "alpine3.17-None-2-${{ runner.os }}-cargo"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build (Release mode)"
        shell: bash
        run: "cargo build --all --release"
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v2
        with:
          crate: "cargo-nextest"
          cache-key: "alpine3.17"
      - name: "Test (Release mode)"
        shell: bash
        run: "cargo nextest run --all --release --no-fail-fast"
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Rename APKs"
        shell: bash
        run: "mv ~/packages/wezterm/x86_64/*.apk $(echo ~/packages/wezterm/x86_64/*.apk | sed -e 's/wezterm-/wezterm-alpine3.17-/')"
      - name: "Move APKs"
        shell: bash
        run: "mv ~/packages/wezterm/x86_64/*.apk ."
      - name: "Move APK keys"
        shell: bash
        run: "mv ~/.abuild/*.pub wezterm-alpine3.17.pub"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "alpine3.17"
          path: "wezterm-*.apk"
