name: fedora35_continuous

on:
  schedule:
    - cron: "10 3 * * *"
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/gen_fedora35_continuous.yml"
      - "assets/fonts/**/*"
      - "assets/icon/*"
      - "assets/open-wezterm-here"
      - "assets/shell-completion/**/*"
      - "assets/shell-integration/**/*"
      - "assets/wezterm-nautilus.py"
      - "assets/wezterm.appdata.xml"
      - "assets/wezterm.desktop"
      - "ci/deploy.sh"
      - "get-deps"
      - "tag-name.sh"
      - "termwiz/data/wezterm.terminfo"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "fedora:35"
    env:
      BUILD_REASON: "Schedule"

    steps:
      - name: "Install config manager"
        shell: bash
        run: "dnf install -y 'dnf-command(config-manager)'"
      - name: "Install git"
        shell: bash
        run: "yum install -y git"
      - name: "Install curl"
        shell: bash
        run: "yum install -y curl"
      - name: "Ensure /run/sshd exists"
        shell: bash
        run: "mkdir -p /run/sshd"
      - name: "Install openssh-server"
        shell: bash
        run: "yum install -y openssh-server"
      - name: "Workaround git permissions issue"
        shell: bash
        run: "git config --global --add safe.directory /__w/wezterm/wezterm"
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: "Cache cargo"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "fedora35-None-2-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build (Release mode)"
        shell: bash
        run: "cargo build --all --release"
      - name: "Test (Release mode)"
        shell: bash
        run: "cargo test --all --release"
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Move RPM"
        shell: bash
        run: "mv ~/rpmbuild/RPMS/*/*.rpm wezterm-nightly-fedora35.rpm"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "fedora35"
          path: "wezterm-*.rpm"
          retention-days: 5

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Workaround git permissions issue"
        shell: bash
        run: "git config --global --add safe.directory /__w/wezterm/wezterm"
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "fedora35"
      - name: "Checksum"
        shell: bash
        run: "for f in wezterm-*.rpm ; do sha256sum $f > $f.sha256 ; done"
      - name: "Upload to Nightly Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber nightly wezterm-*.rpm *.sha256"
