name: macos_continuous

on:
  schedule:
    - cron: "10 3 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - ".cirrus.yml"
      - "docs/**"
      - "ci/build-docs.sh"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - ".github/workflows/pages.yml"
      - ".github/workflows/verify-pages.yml"
      - ".github/workflows/no-response.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"
      - "**/*.markdown"

jobs:
  build:
    runs-on: "macos-11"
    
    env:
      BUILD_REASON: "Schedule"
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
          components: "rustfmt"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Install System Deps"
        shell: bash
        run: "env PATH=$PATH ./get-deps"
      - name: "Build (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin --all --release"
      - name: "Build (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin --all --release"
      - name: "Test (Release mode)"
        shell: bash
        run: "cargo test --target x86_64-apple-darwin --all --release"
      - name: "Package"
        env:
          MACOS_APPLEID: ${{ secrets.MACOS_APPLEID }}
          MACOS_APP_PW: ${{ secrets.MACOS_APP_PW }}
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PW: ${{ secrets.MACOS_CERT_PW }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "macos"
          path: "WezTerm-*.zip"
          retention-days: 5

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "macos"
      - name: "Checksum"
        shell: bash
        run: "for f in WezTerm-*.zip ; do sha256sum $f > $f.sha256 ; done"
      - name: "Upload to Nightly Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber nightly WezTerm-*.zip *.sha256"
