name: centos8_tag

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "centos:8"
    steps:
      - name: "Install config manager"
        shell: bash
        run: "dnf install -y 'dnf-command(config-manager)'"
      - name: "Enable PowerTools"
        shell: bash
        run: "dnf config-manager --set-enabled powertools"
      - name: "Install git"
        shell: bash
        run: "yum install -y git"
      - name: "Install curl"
        shell: bash
        run: "yum install -y curl"
      - name: "Ensure /run/sshd exists"
        shell: bash
        run: "mkdir -p /run/sshd"
      - name: "Install openssh-server"
        shell: bash
        run: "yum install -y openssh-server"
      - name: "checkout repo"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
          components: "rustfmt"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: "Cache cargo"
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "centos8-None-2-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
      - name: "Install System Deps"
        shell: bash
        run: "env PATH=$PATH ./get-deps"
      - name: "Build (Release mode)"
        shell: bash
        run: "cargo build --all --release"
      - name: "Test (Release mode)"
        shell: bash
        run: "cargo test --all --release"
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Move RPM"
        shell: bash
        run: "mv ~/rpmbuild/RPMS/*/*.rpm ."
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "centos8"
          path: "wezterm-*.rpm"

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2
      - name: "Download artifact"
        uses: actions/download-artifact@v2
        with:
          name: "centos8"
      - name: "Create pre-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        shell: bash
        run: "bash ci/retry.sh bash ci/create-release.sh $TAG_NAME"
      - name: "Upload to Tagged Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber $TAG_NAME wezterm-*.rpm"
