name: macos

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/gen_macos.yml"
      - "assets/fonts/**/*"
      - "assets/icon/*"
      - "assets/macos/**/*"
      - "ci/deploy.sh"
      - "ci/macos-entitlement.plist"
      - "ci/tag-name.sh"
      - "get-deps"

jobs:
  build:
    runs-on: "macos-11"
    
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin --all --release"
      - name: "Build (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin --all --release"
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v2
        with:
          crate: "cargo-nextest"
          cache-key: "macos"
      - name: "Test"
        shell: bash
        run: "cargo nextest run --all --no-fail-fast --target=x86_64-apple-darwin"
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "macos"
          path: "WezTerm-*.zip"
