name: macos_tag

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    runs-on: "macos-11"
    
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build (Release mode Intel)"
        shell: bash
        run: "cargo build --target x86_64-apple-darwin --all --release"
      - name: "Build (Release mode ARM)"
        shell: bash
        run: "cargo build --target aarch64-apple-darwin --all --release"
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v2
        with:
          crate: "cargo-nextest"
          cache-key: "macos"
      - name: "Test"
        shell: bash
        run: "cargo nextest run --all --no-fail-fast --target=x86_64-apple-darwin"
      - name: "Package"
        env:
          MACOS_APPLEID: ${{ secrets.MACOS_APPLEID }}
          MACOS_APP_PW: ${{ secrets.MACOS_APP_PW }}
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PW: ${{ secrets.MACOS_CERT_PW }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "macos"
          path: "WezTerm-*.zip"
      - name: "Checkout homebrew tap"
        uses: actions/checkout@v3
        with:
          repository: "wez/homebrew-wezterm"
          path: "homebrew-wezterm"
          token: "${{ secrets.GH_PAT }}"
      - name: "Update homebrew tap formula"
        shell: bash
        run: "cp wezterm.rb homebrew-wezterm/Casks/wezterm.rb"
      - name: "Commit homebrew tap changes"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated update to match latest tag"
          repository: "homebrew-wezterm"

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "macos"
      - name: "Checksum"
        shell: bash
        run: "for f in WezTerm-*.zip ; do sha256sum $f > $f.sha256 ; done"
      - name: "Create pre-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)"
      - name: "Upload to Tagged Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) WezTerm-*.zip *.sha256"
