name: nightly_win

on:
  schedule:
    - cron: "10 * * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [vs2017-win2016]
        rust_toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      shell: cmd
      run: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -yv --default-toolchain ${{ matrix.rust_toolchain }}
          rustup update ${{ matrix.rust_toolchain }}
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
    - name: Package
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        cargo build --release --all
        set BUILD_REASON=Schedule
        bash ci/deploy.sh
    - name: Upload Assets
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: nightly
        # allows comma-separated list of case sensitive globs
        files: "wezterm-*.deb;WezTerm-*.zip;wezterm-*.xz;wezterm-*.rpm;wezterm-*.tar.gz"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

