name: nix_continuous

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '.github/workflows/nix_continuous.yml'
      - 'nix/**'

jobs:
  lints:
    name: Build
    runs-on: ubuntu-latest
    if: github.repository == 'wezterm/wezterm'
    steps:
      - uses: actions/checkout@v3
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache build artifacts
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: ./nix/flake.lock
          ignore-missing-flake-lock: false
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: wezterm
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build default package
        run: |
          nix build ./nix --json \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push wezterm
