name: package_win

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: "10 3 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [vs2017-win2016]
        rust_toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init
    - name: Install Rust
      shell: cmd
      run: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -yv --default-toolchain ${{ matrix.rust_toolchain }}
    - name: Package
      shell: cmd
      run: |
        set path "%USERPROFILE%\.cargo\bin;%PATH"
        cargo build --release --all
        bash ci/deploy.sh
    - name: Move Windows Package
      shell: bash
      run: |
        mkdir pkg_
        mv *.zip pkg_
    - uses: actions/upload-artifact@master
      with:
        name: windows
        path: pkg_
