name: pages

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'
    - 'ci/build-docs.sh'
    - 'ci/generate-docs.py'
    - 'ci/subst-release-info.py'
    - '.github/workflows/pages.yml'
  schedule:
    - cron: "50 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          rustup update stable
      - name: Cache mdBook
        uses: actions/cache@v2.1.6
        with:
          path: ~/mdbook-bin
          key: cargo-bin-mdbook-1
      - name: Install mdBook
        run: |
          mkdir -p ~/mdbook-bin
          (test -x ~/mdbook-bin/mdbook || (cd && cargo install --vers "^0.4" mdbook && cp -p ~/.cargo/bin/mdbook ~/mdbook-bin))
          (test -x ~/mdbook-bin/mdbook-linkcheck || (cd && cargo install mdbook-linkcheck && cp -p ~/.cargo/bin/mdbook-linkcheck ~/mdbook-bin))
      - name: Build
        run: |
          source $HOME/.cargo/env
          PATH="$HOME/mdbook-bin:$PATH"
          ./ci/build-docs.sh
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: gh_pages/html
          keep_history: true
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
