name: tag_posix

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-latest]
        rust_toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install System Deps
      run: sudo ./get-deps
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_toolchain }}
        override: true
    - name: Set macOS deployment target
      run: |
        echo "::set-env name=MACOSX_DEPLOYMENT_TARGET=10.9"
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
    - name: Package
      run: |
        cargo build --release --all
        bash ci/deploy.sh
    - name: Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wezterm-*.rpm
          wezterm-*.deb
          WezTerm-*.zip
          WezTerm-*.AppImage
          wezterm-*.xz
          wezterm-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
