name: tag_win

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [vs2017-win2016]
        rust_toolchain: [x86_64-pc-windows-msvc]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: ${{ matrix.rust_toolchain }}
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-index-${{ hashFiles('Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-cargo-build-target-${{ hashFiles('Cargo.lock') }}
    - name: Package
      shell: cmd
      run: |
        PATH C:\Strawberry\perl\bin;%PATH%
        cargo build --release --all
        bash ci/deploy.sh target/x86_64-pc-windows-msvc
    - name: Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: WezTerm-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

