name: pages

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "ci/build-docs.sh"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - ".github/workflows/verify-pages.yml"
      - ".github/ISSUE_TEMPLATE/*"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          source $HOME/.cargo/env
          rustup update stable
      - name: Cache mdBook
        uses: actions/cache@v1
        with:
          path: ~/mdbook-bin
          key: cargo-bin-mdbook-1
      - name: Install mdBook
        run: |
          mkdir -p ~/mdbook-bin
          (test -x ~/mdbook-bin/mdbook || (cd && cargo install --vers "^0.4" mdbook && cp -p ~/.cargo/bin/mdbook ~/mdbook-bin))
          (test -x ~/mdbook-bin/mdbook-linkcheck || (cd && cargo install mdbook-linkcheck && cp -p ~/.cargo/bin/mdbook-linkcheck ~/mdbook-bin))
      - name: Build
        run: |
          source $HOME/.cargo/env
          PATH="$HOME/mdbook-bin:$PATH"
          ./ci/build-docs.sh

